#!/usr/bin/env python

import sys, time
from daemon import Daemon
from svnnotifier import Notifier

class MyDaemon(Daemon):
    def __init__(self, pidfile, config='.config', stdin='/dev/null', stdout='/dev/null', stderr='/dev/null'):
        Daemon.__init__(self, pidfile, stdin, stdout, stderr)
        self.notifier = Notifier(config)

    def run(self):
        self.notifier.start()

if __name__ == "__main__":
    daemon = MyDaemon('/tmp/svn-notifier.pid')
    
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)
